server:
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: application/json
  port: 5000

logging:
  config: classpath:logback.xml

spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:batchdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    username: local
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

